spring.application.name=Student-Course-Registration-System

# File upload paths
file.upload.path=uploads/payments/
file.upload.materials.path=uploads/materials/

# Multipart settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB